# Generated by Django 4.0.4 on 2022-05-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announs',
            name='Author',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='announs',
            name='header',
            field=models.CharField(max_length=150),
        ),
    ]
