# Generated by Django 4.0.4 on 2022-06-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_authorblog_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announs',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.authorblog'),
        ),
    ]
